# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rack-debug}
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Dollar"]
  s.date = %q{2009-08-31}
  s.description = %q{
Rack::Debug adds a middlerware interface to ruby-debug 
http://github.com/github/rack-debug

}
  s.email = %q{<ddollar@gmail.com>}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "ext/debugger.rb",
     "init.rb",
     "lib/rack/debug.rb",
     "rack-debug.gemspec",
     "tasks/rack-debug.rake"
  ]
  s.homepage = %q{http://github.com/ddollar/rack-debug}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Rack::Debug adds a middlerware interface to ruby-debug}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, [">= 1.0"])
      s.add_runtime_dependency(%q<ruby-debug>, [">= 0.10"])
    else
      s.add_dependency(%q<rack>, [">= 1.0"])
      s.add_dependency(%q<ruby-debug>, [">= 0.10"])
    end
  else
    s.add_dependency(%q<rack>, [">= 1.0"])
    s.add_dependency(%q<ruby-debug>, [">= 0.10"])
  end
end
